apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-task-deployment
  namespace: aditya-namespace
  labels:
    app: flask-task-manager

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flask-task-manager

  template:
    metadata:
      labels:
        app: flask-task-manager

    spec:
      containers:
        - name: flask-task-manager
          image: aditya0910/flask-task-manager:latest

          ports:
            - containerPort: 5000

          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres-service:5432/tasksdb

          volumeMounts:
            - name: flask-storage
              mountPath: /app/data

      volumes:
        - name: flask-storage
          persistentVolumeClaim:
            claimName: flask-app-pvc
